/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:d470a854-03be-47f8-842e-c59ffd550402",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_DGRVZO8Mb",
    "aws_user_pools_web_client_id": "267a5qgci2djfasa20c6dprbl",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://diwyeox3wnacbbcl4nc6ozao6q.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-7fcwz6zo5zf7pcbijcu6amqjs4",
    "aws_user_files_s3_bucket": "mzrezimages01124634-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
